apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dhivakarvb/devops.git
    targetRevision: main
    path: Task6/infra-repo/k8s   # <-- corrected path
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
 