apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dhivakarvb/devops/Task6/infra-repo/k8s.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
