name: Deploy Node.js App

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Copy project files to EC2
        run: |
          rsync -avz --exclude '.git' ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }}:/tmp/app

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} "
            set -e
            APP_DIR=/opt/app/node
            sudo mkdir -p \$APP_DIR
            sudo rm -rf \$APP_DIR/*
            sudo cp -r /tmp/app/* \$APP_DIR/
            cd \$APP_DIR
            npm install --production
            nohup node server.js > app.log 2>&1 &
          "
